### ISSUE TITLE
cannot compile with dmd2057

### ISSUE THREAD

**Issue by extrawurst** [Trass3r/cl4d#2]
after commenting out the CLObjectCollection destructor like said in issue #1 i still cant build cl4d:

opencl\memory.d(164): Error: function opencl.c.cl.clGetMemObjectInfo (const(void_) memobj, uint param_name, uint param_value_size, void_ param_value, uint\* param_value_size_ret) is not callable using argument types (const(void_),uint,uint,const(void_)_,typeof(null))
opencl\memory.d(164): Error: cannot implicitly convert expression (& info) of type const(void_)\* to void*
opencl\buffer.d(102): Error: template instance opencl.memory.CLMemory.getInfo!(const(void*),clGetMemObjectInfo) error instantiating

**Comment by Trass3r** [comment]
How/What did you compile?
Something like `dmd -d -lib opencl/*.d` works fine for me.

**Comment by extrawurst** [comment]
oh i see u use -d. i converted the last few typedefs to alias and compiled without -d then it is broken. when revert the aliases and use -d it works fine. but that foreces me to use -d in my whole project wich kind of sucks. wouldn't it be better to convert to alias ?

**Comment by Trass3r** [comment]
You loose every type-safety with alias. What's so bad about -d?
Once there is a library based typedef I will change it to that.
