### ISSUE TITLE
How to get libOpenCL.a?

### ISSUE THREAD

**Issue by NCrashed** [Trass3r/cl4d#4]
How did you get OpenCL.lib? I need equalent for linux platform to provide crosspaltfom support.

**Comment by Trass3r** [comment]
Created it with implib. Shouldn't it be enough to compile with -lOpenCL?

**Comment by NCrashed** [comment]
No, it is not enough. The best way is to handle dynamic bindings to OpenCL like https://github.com/Trass3r/cl4d/issues/5

**Comment by Trass3r** [comment]
Ok closing this one then.
